// Generated from: all-tested-systems\banking\tests\test-features\accounts-tests.feature
import { test } from "../../../../../all-tested-systems/banking/helpers/fixtures.ts";

test.describe('Accounts Page Test Scenarios', () => {

  test.beforeEach('Background: Common steps for all Scenarios', async ({ Given, When, page }, testInfo) => { if (testInfo.error) return;
    await Given('The "ADMIN_USER" is logged in the banking system', null, { page }); 
    await When('The user is navigated to the "Accounts" Page', null, { page }); 
  });
  
  test.describe('[TC-ACC-01] Create A New Account', () => {

    test('Example #1', { tag: ['@accounts', '@banking', '@regress'] }, async ({ When, Then, And, page }) => { 
      await When('The user is navigated to the "Dashboard" Page', null, { page }); 
      await And('The user clicks "ADD_ACCOUNT" button on the dashboard page', null, { page }); 
      await And('The user saves the form for "Savings" Account type with mandatory fields filled in', null, { page }); 
      await Then('The new "Savings" account is created', null, { page }); 
    });

    test('Example #2', { tag: ['@accounts', '@banking', '@regress'] }, async ({ When, Then, And, page }) => { 
      await When('The user is navigated to the "Dashboard" Page', null, { page }); 
      await And('The user clicks "ADD_ACCOUNT" button on the dashboard page', null, { page }); 
      await And('The user saves the form for "Checking" Account type with mandatory fields filled in', null, { page }); 
      await Then('The new "Checking" account is created', null, { page }); 
    });

    test('Example #3', { tag: ['@accounts', '@banking', '@regress'] }, async ({ When, Then, And, page }) => { 
      await When('The user is navigated to the "Dashboard" Page', null, { page }); 
      await And('The user clicks "ADD_ACCOUNT" button on the dashboard page', null, { page }); 
      await And('The user saves the form for "Credit_Card" Account type with mandatory fields filled in', null, { page }); 
      await Then('The new "Credit_Card" account is created', null, { page }); 
    });

  });

  test('[TC-ACC-02] Create New Account Is Not Possible Without Filling Mandatory Fields', { tag: ['@accounts', '@banking', '@regress'] }, async ({ When, Then, And, page }) => { 
    await When('The user is navigated to the "Dashboard" Page', null, { page }); 
    await And('The user clicks "ADD_ACCOUNT" button on the dashboard page', null, { page }); 
    await And('The user tries to save the form only with optional fields filled in', null, { page }); 
    await Then('The system writes error messages under the empty mandatory fields', null, { page }); 
  });

  test('[TC-ACC-03] Edit Account Name With Edit Button', { tag: ['@accounts', '@banking', '@regress'] }, async ({ When, Then, And, page }) => { 
    await When('The user clicks "EDIT" button on the accounts page', null, { page }); 
    await And('The user updates account name', null, { page }); 
    await Then('The account is upated', null, { page }); 
  });

  test('[TC-ACC-04] Delete Account And Verify It Is Removed', { tag: ['@accounts', '@banking', '@regress'] }, async ({ When, Then, And, contextData, page }) => { 
    await When('The user checks the account number of an account he wants to delete', null, { contextData, page }); 
    await And('The user clicks "DELETE" button on the accounts page', null, { page }); 
    await And('The user clicks "CANCEL" button on the accounts page', null, { page }); 
    await And('The user clicks "DELETE" button on the accounts page', null, { page }); 
    await And('The user clicks "CONFIRM_DELETE" button on the accounts page', null, { page }); 
    await Then('The account is deleted', null, { contextData, page }); 
  });

  test.describe('[TC-ACC-05] Filter Accounts By Account Type', () => {

    test('Example #1', { tag: ['@accounts', '@banking', '@regress'] }, async ({ When, Then, And, contextData, page }) => { 
      await When('The user creates all account types', null, { page }); 
      await And('The user checks number of accounts listed on the page', null, { contextData, page }); 
      await And('The user selects "Savings" account type', null, { page }); 
      await Then('The user verifies that only "Savings" account types are visible', null, { page }); 
      await When('The user resets filter', null, { page }); 
      await Then('All account types are listed', null, { contextData, page }); 
    });

    test('Example #2', { tag: ['@accounts', '@banking', '@regress'] }, async ({ When, Then, And, contextData, page }) => { 
      await When('The user creates all account types', null, { page }); 
      await And('The user checks number of accounts listed on the page', null, { contextData, page }); 
      await And('The user selects "Checking" account type', null, { page }); 
      await Then('The user verifies that only "Checking" account types are visible', null, { page }); 
      await When('The user resets filter', null, { page }); 
      await Then('All account types are listed', null, { contextData, page }); 
    });

    test('Example #3', { tag: ['@accounts', '@banking', '@regress'] }, async ({ When, Then, And, contextData, page }) => { 
      await When('The user creates all account types', null, { page }); 
      await And('The user checks number of accounts listed on the page', null, { contextData, page }); 
      await And('The user selects "Credit" account type', null, { page }); 
      await Then('The user verifies that only "Credit" account types are visible', null, { page }); 
      await When('The user resets filter', null, { page }); 
      await Then('All account types are listed', null, { contextData, page }); 
    });

  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('all-tested-systems\\banking\\tests\\test-features\\accounts-tests.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":13,"pickleLine":16,"tags":["@accounts","@banking","@regress"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given The \"ADMIN_USER\" is logged in the banking system","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"ADMIN_USER\"","children":[{"start":5,"value":"ADMIN_USER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When The user is navigated to the \"Accounts\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":29,"value":"\"Accounts\"","children":[{"start":30,"value":"Accounts","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":14,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When The user is navigated to the \"Dashboard\" Page","stepMatchArguments":[{"group":{"start":29,"value":"\"Dashboard\"","children":[{"start":30,"value":"Dashboard","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":15,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"And The user clicks \"ADD_ACCOUNT\" button on the dashboard page","stepMatchArguments":[{"group":{"start":16,"value":"\"ADD_ACCOUNT\"","children":[{"start":17,"value":"ADD_ACCOUNT","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":16,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"And The user saves the form for \"Savings\" Account type with mandatory fields filled in","stepMatchArguments":[{"group":{"start":28,"value":"\"Savings\"","children":[{"start":29,"value":"Savings","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":17,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then The new \"Savings\" account is created","stepMatchArguments":[{"group":{"start":8,"value":"\"Savings\"","children":[{"start":9,"value":"Savings","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":20,"pickleLine":17,"tags":["@accounts","@banking","@regress"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given The \"ADMIN_USER\" is logged in the banking system","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"ADMIN_USER\"","children":[{"start":5,"value":"ADMIN_USER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When The user is navigated to the \"Accounts\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":29,"value":"\"Accounts\"","children":[{"start":30,"value":"Accounts","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":21,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When The user is navigated to the \"Dashboard\" Page","stepMatchArguments":[{"group":{"start":29,"value":"\"Dashboard\"","children":[{"start":30,"value":"Dashboard","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":22,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"And The user clicks \"ADD_ACCOUNT\" button on the dashboard page","stepMatchArguments":[{"group":{"start":16,"value":"\"ADD_ACCOUNT\"","children":[{"start":17,"value":"ADD_ACCOUNT","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":23,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"And The user saves the form for \"Checking\" Account type with mandatory fields filled in","stepMatchArguments":[{"group":{"start":28,"value":"\"Checking\"","children":[{"start":29,"value":"Checking","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":24,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then The new \"Checking\" account is created","stepMatchArguments":[{"group":{"start":8,"value":"\"Checking\"","children":[{"start":9,"value":"Checking","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":27,"pickleLine":18,"tags":["@accounts","@banking","@regress"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given The \"ADMIN_USER\" is logged in the banking system","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"ADMIN_USER\"","children":[{"start":5,"value":"ADMIN_USER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When The user is navigated to the \"Accounts\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":29,"value":"\"Accounts\"","children":[{"start":30,"value":"Accounts","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":28,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When The user is navigated to the \"Dashboard\" Page","stepMatchArguments":[{"group":{"start":29,"value":"\"Dashboard\"","children":[{"start":30,"value":"Dashboard","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":29,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"And The user clicks \"ADD_ACCOUNT\" button on the dashboard page","stepMatchArguments":[{"group":{"start":16,"value":"\"ADD_ACCOUNT\"","children":[{"start":17,"value":"ADD_ACCOUNT","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":30,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"And The user saves the form for \"Credit_Card\" Account type with mandatory fields filled in","stepMatchArguments":[{"group":{"start":28,"value":"\"Credit_Card\"","children":[{"start":29,"value":"Credit_Card","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":31,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then The new \"Credit_Card\" account is created","stepMatchArguments":[{"group":{"start":8,"value":"\"Credit_Card\"","children":[{"start":9,"value":"Credit_Card","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":36,"pickleLine":21,"tags":["@accounts","@banking","@regress"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given The \"ADMIN_USER\" is logged in the banking system","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"ADMIN_USER\"","children":[{"start":5,"value":"ADMIN_USER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When The user is navigated to the \"Accounts\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":29,"value":"\"Accounts\"","children":[{"start":30,"value":"Accounts","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":22,"keywordType":"Action","textWithKeyword":"When The user is navigated to the \"Dashboard\" Page","stepMatchArguments":[{"group":{"start":29,"value":"\"Dashboard\"","children":[{"start":30,"value":"Dashboard","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":38,"gherkinStepLine":23,"keywordType":"Action","textWithKeyword":"And The user clicks \"ADD_ACCOUNT\" button on the dashboard page","stepMatchArguments":[{"group":{"start":16,"value":"\"ADD_ACCOUNT\"","children":[{"start":17,"value":"ADD_ACCOUNT","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":24,"keywordType":"Action","textWithKeyword":"And The user tries to save the form only with optional fields filled in","stepMatchArguments":[]},{"pwStepLine":40,"gherkinStepLine":25,"keywordType":"Outcome","textWithKeyword":"Then The system writes error messages under the empty mandatory fields","stepMatchArguments":[]}]},
  {"pwTestLine":43,"pickleLine":28,"tags":["@accounts","@banking","@regress"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given The \"ADMIN_USER\" is logged in the banking system","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"ADMIN_USER\"","children":[{"start":5,"value":"ADMIN_USER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When The user is navigated to the \"Accounts\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":29,"value":"\"Accounts\"","children":[{"start":30,"value":"Accounts","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":44,"gherkinStepLine":29,"keywordType":"Action","textWithKeyword":"When The user clicks \"EDIT\" button on the accounts page","stepMatchArguments":[{"group":{"start":16,"value":"\"EDIT\"","children":[{"start":17,"value":"EDIT","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":30,"keywordType":"Action","textWithKeyword":"And The user updates account name","stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":31,"keywordType":"Outcome","textWithKeyword":"Then The account is upated","stepMatchArguments":[]}]},
  {"pwTestLine":49,"pickleLine":34,"tags":["@accounts","@banking","@regress"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given The \"ADMIN_USER\" is logged in the banking system","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"ADMIN_USER\"","children":[{"start":5,"value":"ADMIN_USER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When The user is navigated to the \"Accounts\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":29,"value":"\"Accounts\"","children":[{"start":30,"value":"Accounts","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":50,"gherkinStepLine":35,"keywordType":"Action","textWithKeyword":"When The user checks the account number of an account he wants to delete","stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":36,"keywordType":"Action","textWithKeyword":"And The user clicks \"DELETE\" button on the accounts page","stepMatchArguments":[{"group":{"start":16,"value":"\"DELETE\"","children":[{"start":17,"value":"DELETE","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":52,"gherkinStepLine":37,"keywordType":"Action","textWithKeyword":"And The user clicks \"CANCEL\" button on the accounts page","stepMatchArguments":[{"group":{"start":16,"value":"\"CANCEL\"","children":[{"start":17,"value":"CANCEL","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":53,"gherkinStepLine":38,"keywordType":"Action","textWithKeyword":"And The user clicks \"DELETE\" button on the accounts page","stepMatchArguments":[{"group":{"start":16,"value":"\"DELETE\"","children":[{"start":17,"value":"DELETE","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":54,"gherkinStepLine":39,"keywordType":"Action","textWithKeyword":"And The user clicks \"CONFIRM_DELETE\" button on the accounts page","stepMatchArguments":[{"group":{"start":16,"value":"\"CONFIRM_DELETE\"","children":[{"start":17,"value":"CONFIRM_DELETE","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":55,"gherkinStepLine":40,"keywordType":"Outcome","textWithKeyword":"Then The account is deleted","stepMatchArguments":[]}]},
  {"pwTestLine":60,"pickleLine":52,"tags":["@accounts","@banking","@regress"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given The \"ADMIN_USER\" is logged in the banking system","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"ADMIN_USER\"","children":[{"start":5,"value":"ADMIN_USER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When The user is navigated to the \"Accounts\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":29,"value":"\"Accounts\"","children":[{"start":30,"value":"Accounts","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":44,"keywordType":"Action","textWithKeyword":"When The user creates all account types","stepMatchArguments":[]},{"pwStepLine":62,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"And The user checks number of accounts listed on the page","stepMatchArguments":[]},{"pwStepLine":63,"gherkinStepLine":46,"keywordType":"Action","textWithKeyword":"And The user selects \"Savings\" account type","stepMatchArguments":[{"group":{"start":17,"value":"\"Savings\"","children":[{"start":18,"value":"Savings","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":64,"gherkinStepLine":47,"keywordType":"Outcome","textWithKeyword":"Then The user verifies that only \"Savings\" account types are visible","stepMatchArguments":[{"group":{"start":28,"value":"\"Savings\"","children":[{"start":29,"value":"Savings","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":65,"gherkinStepLine":48,"keywordType":"Action","textWithKeyword":"When The user resets filter","stepMatchArguments":[]},{"pwStepLine":66,"gherkinStepLine":49,"keywordType":"Outcome","textWithKeyword":"Then All account types are listed","stepMatchArguments":[]}]},
  {"pwTestLine":69,"pickleLine":53,"tags":["@accounts","@banking","@regress"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given The \"ADMIN_USER\" is logged in the banking system","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"ADMIN_USER\"","children":[{"start":5,"value":"ADMIN_USER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When The user is navigated to the \"Accounts\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":29,"value":"\"Accounts\"","children":[{"start":30,"value":"Accounts","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":70,"gherkinStepLine":44,"keywordType":"Action","textWithKeyword":"When The user creates all account types","stepMatchArguments":[]},{"pwStepLine":71,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"And The user checks number of accounts listed on the page","stepMatchArguments":[]},{"pwStepLine":72,"gherkinStepLine":46,"keywordType":"Action","textWithKeyword":"And The user selects \"Checking\" account type","stepMatchArguments":[{"group":{"start":17,"value":"\"Checking\"","children":[{"start":18,"value":"Checking","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":73,"gherkinStepLine":47,"keywordType":"Outcome","textWithKeyword":"Then The user verifies that only \"Checking\" account types are visible","stepMatchArguments":[{"group":{"start":28,"value":"\"Checking\"","children":[{"start":29,"value":"Checking","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":74,"gherkinStepLine":48,"keywordType":"Action","textWithKeyword":"When The user resets filter","stepMatchArguments":[]},{"pwStepLine":75,"gherkinStepLine":49,"keywordType":"Outcome","textWithKeyword":"Then All account types are listed","stepMatchArguments":[]}]},
  {"pwTestLine":78,"pickleLine":54,"tags":["@accounts","@banking","@regress"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given The \"ADMIN_USER\" is logged in the banking system","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"ADMIN_USER\"","children":[{"start":5,"value":"ADMIN_USER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When The user is navigated to the \"Accounts\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":29,"value":"\"Accounts\"","children":[{"start":30,"value":"Accounts","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":79,"gherkinStepLine":44,"keywordType":"Action","textWithKeyword":"When The user creates all account types","stepMatchArguments":[]},{"pwStepLine":80,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"And The user checks number of accounts listed on the page","stepMatchArguments":[]},{"pwStepLine":81,"gherkinStepLine":46,"keywordType":"Action","textWithKeyword":"And The user selects \"Credit\" account type","stepMatchArguments":[{"group":{"start":17,"value":"\"Credit\"","children":[{"start":18,"value":"Credit","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":82,"gherkinStepLine":47,"keywordType":"Outcome","textWithKeyword":"Then The user verifies that only \"Credit\" account types are visible","stepMatchArguments":[{"group":{"start":28,"value":"\"Credit\"","children":[{"start":29,"value":"Credit","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":83,"gherkinStepLine":48,"keywordType":"Action","textWithKeyword":"When The user resets filter","stepMatchArguments":[]},{"pwStepLine":84,"gherkinStepLine":49,"keywordType":"Outcome","textWithKeyword":"Then All account types are listed","stepMatchArguments":[]}]},
]; // bdd-data-end